#!/bin/bash
#$ -N W01_phase_per_chrom
#$ -l h_data=4G,h_rt=24:00:00
#$ -pe shared 6
#$ -t 1-18:1
#$ -hold_jid W00b_merge_wg
#$ -o /u/project/cluo/terencew/claude/project_ideas/asm_lr/logs/W01/W01_phase_per_chrom.$JOB_ID.$TASK_ID
#$ -e /u/project/cluo/terencew/claude/project_ideas/asm_lr/logs/W01/W01_phase_per_chrom.$JOB_ID.$TASK_ID
#$ -cwd

# WhatsHap haplotagging — one task per sample, loops over all 22 autosomes
# internally (resumable: skips any chrom already present+indexed, so safe
# to resubmit if it dies partway through).
#
# Consolidated from three incremental historical patches (old/fix/W01_phase_wg.sh,
# old/fix/W01h_fix_phase_wg.sh, old/fix/W01i_fix_phase_wg.sh) that were applied
# one sample/task at a time to fix specific failures in the original run.
# This version folds in the fixes (correct by_chrom/ output path, post-loop
# completeness check, quickcheck) and generalizes back to all 18 samples via
# txt/samples/final_samples.txt, so it works as a normal from-scratch
# pipeline stage again, not just a one-off patch. All 18 samples' outputs
# already exist from those historical runs -- this doesn't need to be rerun
# unless a sample is added or output is lost.
#
# VCF source per sample (from csv/meta/cohort_downloads.tsv, vcf_source
# column): all 18 samples now use the 1000G 3202 phased panel; per-chrom het
# VCFs are pre-generated by D02_download_1kg_phased_vcf.sh under
# vcf/read_based/, falling back to streaming from EBI HTTPS if missing.
#
# Output: bam/haplotagged/by_chrom/{SAMPLE}_{chrom}_haplotagged.bam (+.bai)
# Next:   W01g_merge_haplotagged_wg.sh merges the 22 chroms into one
#         whole-genome haplotagged BAM per sample.

set -euo pipefail

source /u/home/t/terencew/project-cluo/miniconda3/bin/activate whatshap-env

PROJDIR=/u/project/cluo/terencew/claude/project_ideas/asm_lr
MANIFEST=$PROJDIR/csv/meta/cohort_downloads.tsv

BCFTOOLS=/u/local/apps/bcftools/1.11/gcc-4.8.5/bin/bcftools
SAMTOOLS=/u/local/apps/samtools/1.15/gcc-4.8.5/bin/samtools
REF=/u/project/cluo/terencew/reference/hg38_igvf/GRCh38.autosome.fa
SCRATCH=/u/project/cluo_scratch/terencew/claude/asm_lr/wg_phase
BYDIR=$PROJDIR/bam/haplotagged/by_chrom

mkdir -p "$BYDIR" "$SCRATCH"

SAMPLES=($(cat $PROJDIR/txt/samples/final_samples.txt))
ID=$SGE_TASK_ID
SAMPLE=${SAMPLES[$((ID - 1))]}
VCF_SRC=$(awk -F'\t' -v s="$SAMPLE" '$1==s {print $10}' "$MANIFEST")

BAM=$PROJDIR/bam/merged_bam/${SAMPLE}_wg.bam

echo "$(date): W01 task $ID — $SAMPLE"
echo "Hostname: $(hostname)"
echo "VCF source: $VCF_SRC"

if [ ! -f "$BAM" ]; then
    echo "ERROR: $BAM not found — run W00a_align_ubam.sh + W00b_merge_wg.sh first"
    exit 1
fi

CHROMS=(chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 \
        chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 \
        chr20 chr21 chr22)

time for CHROM in "${CHROMS[@]}"; do
    OUT_TAGGED=$BYDIR/${SAMPLE}_${CHROM}_haplotagged.bam

    if [ -f "$OUT_TAGGED" ] && [ -s "$OUT_TAGGED" ] && [ -f "${OUT_TAGGED}.bai" ]; then
        echo "$(date): $CHROM — exists, skipping"
        continue
    fi

    HET_VCF=$PROJDIR/vcf/read_based/${SAMPLE}_${CHROM}_het_snps.vcf.gz
    if [ ! -f "$HET_VCF" ] || [ ! -f "${HET_VCF}.tbi" ]; then
        echo "$(date): $CHROM — het VCF missing, streaming from EBI HTTPS..."
        CHROM_VCF=$(echo "$VCF_SRC" | sed "s/{chr}/$CHROM/g")
        curl -s "$CHROM_VCF" | $BCFTOOLS view -s "$SAMPLE" -g het - | bgzip > "$HET_VCF"
        tabix "$HET_VCF"
        N_SITES=$(zcat "$HET_VCF" | grep -cv "^#" || true)
        echo "$(date): $CHROM — $N_SITES het SNPs"
    fi

    echo "$(date): $CHROM — haplotagging..."
    TMP_BAM=$SCRATCH/${SAMPLE}_${CHROM}_haplotagged_tmp.bam
    rm -f "$TMP_BAM"

    time whatshap haplotag \
        --ignore-read-groups \
        --reference "$REF" \
        --regions "$CHROM" \
        --output-threads 6 \
        --output "$TMP_BAM" \
        "$HET_VCF" \
        "$BAM"

    time $SAMTOOLS sort -@ 6 -o "$OUT_TAGGED" "$TMP_BAM" && rm -f "$TMP_BAM"
    time $SAMTOOLS index "$OUT_TAGGED"

    HP1=$($SAMTOOLS view -F 4 "$OUT_TAGGED" "$CHROM" | awk '/HP:i:1/{n++} END{print n+0}')
    HP2=$($SAMTOOLS view -F 4 "$OUT_TAGGED" "$CHROM" | awk '/HP:i:2/{n++} END{print n+0}')
    echo "$(date): $CHROM done — HP1=$HP1  HP2=$HP2"
done

echo "$(date): checking all 22 chrom BAMs are present+indexed for $SAMPLE..."
MISSING=0
for CHROM in "${CHROMS[@]}"; do
    f=$BYDIR/${SAMPLE}_${CHROM}_haplotagged.bam
    if [ ! -f "$f" ] || [ ! -f "${f}.bai" ]; then
        echo "  MISSING or unindexed: $f"
        MISSING=$((MISSING + 1))
    fi
done
if [ "$MISSING" -gt 0 ]; then
    echo "ERROR: $MISSING chrom BAMs missing or unindexed for $SAMPLE"
    exit 1
fi

echo "$(date): W01 done — $SAMPLE — all 22 chroms haplotagged"
echo "Next: qsub scripts/wg/W01g_merge_haplotagged_wg.sh"
