#!/bin/bash
#$ -N W02_phase_wg
#$ -l h_data=8G,h_rt=8:00:00
#$ -pe shared 4
#$ -o /u/project/cluo/terencew/claude/project_ideas/asm_lr/logs/NA21093/W02_phase_wg.$JOB_ID
#$ -e /u/project/cluo/terencew/claude/project_ideas/asm_lr/logs/NA21093/W02_phase_wg.$JOB_ID
#$ -hold_jid W00_align_wg
#$ -cwd

# WhatsHap haplotagging — one task per sample, loops over all 22 autosomes.
# VCF source per sample (from manifest vcf_source column):
#   Y1 samples (8): HPRC assembly-backed dipcall VCF — assembly-level phase blocks,
#                   essentially no switch errors within contigs (N50 ~40-60 Mb)
#   R2 samples (22): 1000G 3202 phased panel — SHAPEIT4 statistical phasing,
#                    99.95% concordant with dipcall at shared sites (chr19 benchmark)
#
# For Y1 samples the dipcall VCF must exist locally at vcf/read_based/{SAMPLE}_dip.vcf.gz
# (produced by D01_download_hprc_assembly_vcf.sh).
# For 1000G samples the VCF is streamed per-chromosome from S3 at runtime.
#
# Output: bam/{SAMPLE}_{chrom}_haplotagged.bam (+.bai) for chr1–chr22

set -euo pipefail

source /u/home/t/terencew/project-cluo/miniconda3/bin/activate whatshap-env

PROJDIR=/u/project/cluo/terencew/claude/project_ideas/asm_lr
MANIFEST=$PROJDIR/csv/meta/cohort_downloads.tsv

BCFTOOLS=/u/local/apps/bcftools/1.11/gcc-4.8.5/bin/bcftools
SAMTOOLS=/u/local/apps/samtools/1.15/gcc-4.8.5/bin/samtools
REF=/u/project/cluo/terencew/reference/hg38_igvf/GRCh38.autosome.fa
SCRATCH=/u/project/cluo_scratch/terencew/claude/asm_lr/wg_phase

mkdir -p $PROJDIR/vcf/read_based $PROJDIR/bam $SCRATCH $PROJDIR/logs

SAMPLE=NA21093
VCF_SRC=$(awk -F'\t' -v s="$SAMPLE" '$1==s {print $10}' "$MANIFEST")

BAM=$PROJDIR/bam/${SAMPLE}_wg.bam

echo "$(date): W02 — $SAMPLE"
echo "Hostname: $(hostname)"
echo "VCF source: $VCF_SRC"

if [ ! -f "$BAM" ]; then
    echo "ERROR: $BAM not found — run W00_align_wg.sh first"
    exit 1
fi

# All samples now use 1000G phased panel (standardized).
# Per-sample per-chrom het VCFs are pre-generated by D02_download_1kg_phased_vcf.sh.
# This script uses them directly; if missing, falls back to streaming from S3.
echo "$(date): using 1000G phased panel (pre-generated het VCFs preferred)"

CHROMS=(chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 \
        chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 \
        chr20 chr21 chr22)

for CHROM in "${CHROMS[@]}"; do
    OUT_TAGGED=$PROJDIR/bam/${SAMPLE}_${CHROM}_haplotagged.bam

    if [ -f "$OUT_TAGGED" ] && [ -s "$OUT_TAGGED" ]; then
        echo "$(date): $CHROM — exists, skipping"
        continue
    fi

    echo "$(date): $CHROM — extracting het SNPs..."

    HET_VCF=$PROJDIR/vcf/read_based/${SAMPLE}_${CHROM}_het_snps.vcf.gz
    if [ ! -f "$HET_VCF" ] || [ ! -f "${HET_VCF}.tbi" ]; then
        # Fallback: stream from EBI via curl (slow — prefer running D02 first)
        echo "$(date): $CHROM — het VCF missing, streaming from EBI HTTPS..."
        CHROM_VCF=$(echo "$VCF_SRC" | sed "s/{chr}/$CHROM/g")
        curl -s "$CHROM_VCF" | $BCFTOOLS view -s "$SAMPLE" -g het - | bgzip > "$HET_VCF"
        tabix "$HET_VCF"
        N_SITES=$(zcat "$HET_VCF" | grep -cv "^#" || true)
        echo "$(date): $CHROM — $N_SITES het SNPs"
    fi

    echo "$(date): $CHROM — haplotagging..."
    TMP_BAM=$SCRATCH/${SAMPLE}_${CHROM}_haplotagged_tmp.bam
    time whatshap haplotag \
        --ignore-read-groups \
        --reference "$REF" \
        --regions "$CHROM" \
        --output-threads 4 \
        --output "$TMP_BAM" \
        "$HET_VCF" \
        "$BAM"

    $SAMTOOLS sort -@ 4 -o "$OUT_TAGGED" "$TMP_BAM" && rm -f "$TMP_BAM"
    $SAMTOOLS index "$OUT_TAGGED"

    HP1=$($SAMTOOLS view -F 4 "$OUT_TAGGED" "$CHROM" | awk '/HP:i:1/{n++} END{print n+0}')
    HP2=$($SAMTOOLS view -F 4 "$OUT_TAGGED" "$CHROM" | awk '/HP:i:2/{n++} END{print n+0}')
    echo "$(date): $CHROM done — HP1=$HP1  HP2=$HP2"
done

echo "$(date): W02 done — $SAMPLE all chroms haplotagged"
echo "Next: qsub scripts/wg/W03_modkit_pileup.sh"
